services:
  - type: web
    name: nivest-ai-backend
    runtime: docker
    region: singapore
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: https://nivestai-demo-38721.netlify.app,http://localhost:5173,http://127.0.0.1:5173
      - key: ENABLE_LIVE_MARKET
        value: "1"
      - key: ENABLE_LIVE_NEWS
        value: "1"
      - key: GROQ_API_KEY
        sync: false
